### ISSUE TITLE
 Bluetooth not discoverable in raspberry pi 3 model B+

### ISSUE THREAD

**Issue by mvenilton** [balena-io-projects/balena-sound#10]
Works like a charm in raspberry pi 3 model B, but in model B+ the bluetooth is not discoverable in phone or pc.

**Comment by Nytrouz-official** [comment]
I just played a little bit with the lock overdrive button dont know what it does but now my mobilephone is conected
(pi3 B+ same issue)

**Comment by chrisys** [comment]
@mvenilton interesting! I just deployed to a new 3B+ and see the same thing.

If you use the dashboard terminal and run `bluetoothctl` and then `show` you can see the discoverable status. You can also force it on by running `discoverable on`. I will take a look to see if I can figure out why this is happening.

**Comment by chrisys** [comment]
You should find this now works ok with v0.0.10 - can you give it a try and reopen this issue if not?

**Comment by mvenilton** [comment]
> 
> 
> You should find this now works ok with v0.0.10 - can you give it a try and reopen this issue if not?

Thanks @chrisys This is working!

**Comment by Nytrouz-official** [comment]
how do I update to the new version do I just push it ore do I have to delete the old one?

**Comment by chrisys** [comment]
@Nytrouz-official you can download the new version from GitHub and push it again to your device, you don't have to flash the SD card or delete anything. The build system will recognise that it's only a small change.

**Comment by Nytrouz-official** [comment]
ok thanks
