### ISSUE TITLE
Need Pairing Password

### ISSUE THREAD

**Issue by ibaxx** [balena-io-projects/balena-sound#20]
I have setup a balena sound device.
It does it job but I am living in a flat and my neighbours can connect to the device, because there is no Password set to pair.

Thats a big issue!

**Comment by barhun** [comment]
#34 offers a solution.

**Comment by AlexProgrammerDE** [comment]
@ibaxx i have implemented a solution in #48

**Comment by tmigone** [comment]
PIN code support was implemented on #51. There are some quirks with apple devices (won't work on iOS due to apple security restrictions). Closing this issue.
