### ISSUE TITLE
Add Code to toggle pio pin when bluetooth is connected or when sound is playing

### ISSUE THREAD

**Issue by johnborgesfl** [balena-io-projects/balena-sound#22]
This will let us control an external amplifier and turn it on when bluetooth pairs.

Volumio has an add-in that does this and it worked great

**Comment by AlexProgrammerDE** [comment]
I dont't understand your request. Do you mean that when a bluetooth device connects a GPIO pin gets activated/disabled?

**Comment by johnborgesfl** [comment]
yes, when a bluetooth device connects, toggle a gpio pin.  this can be used
to with a relay to turn on an external amplifier or perhaps switch inputs

Volumio has this capability for Airplay but they do not implement a
bluetooth receiver.

**Comment by AlexProgrammerDE** [comment]
I think i just need to add a line in: https://github.com/balena-io-projects/balena-sound/blob/master/bluetooth-audio/bluetooth-udev which runs when a bluetooth device pairs and disconnects.

**Comment by AlexProgrammerDE** [comment]
How do you need it? Should the GPIO pin turned off when the device disconnects or should he stay on? And which pin do you want to use?

**Comment by johnborgesfl** [comment]
The way the volumio implements it is with an addin that you can configure
which pin # you want and if you want it normally off or normally on so as
to provide the most flexibility as to what relay you are using.
Since this is a dedicated player you can perhaps program in any available
two gpio pins one NO and another NC so as avoid a configuration screen
menu. I just need t

**Comment by AlexProgrammerDE** [comment]
@johnborgesfl I think i found a solution. I can use python to control the GPIO Pins with gpiozero. Python has all functions for implementing it so it could work.

**Comment by tmigone** [comment]
@AlexProgrammerDE implemented this on #56
