### ISSUE TITLE
Does it support Raspi4?

### ISSUE THREAD

**Issue by alchip** [balena-io-projects/balena-sound#25]
Does it support Raspi4? I encounter below message when upload.
bluetooth-audio]  apt failed, retrying
[bluetooth-audio]  Reading package lists...
[bluetooth-audio]  Building dependency tree...
[bluetooth-audio]  Reading state information...
[bluetooth-audio]  E: Unable to locate package bluealsa
[bluetooth-audio]  
[bluetooth-audio]  Removing intermediate container d6e217f4167a
[bluetooth-audio]  The command '/bin/sh -c install_packages   alsa-utils   bluealsa   bluez   python-gobject   python-dbus   mplayer' returned a non-zero code: 100
[Info]             Uploading images
[Success]          Successfully uploaded images
[Error]            Some services failed to build:
[Error]              Service: bluetooth-audio
[Error]                Error: The command '/bin/sh -c install_packages   alsa-utils   bluealsa   bluez   python-gobject   python-dbus   mplayer' returned a non-zero code: 100
[Info]             Built on arm03
[Error]            Not deploying release.
Remote build failed

**Comment by chrisys** [comment]
Right now the project does not support the 64-bit OS which is the only one available for Pi 4, so it doesn't currently work with Pi 4.
