### ISSUE TITLE
Set up PIN code with an environment variable

### ISSUE THREAD

**Issue by barhun** [balena-io-projects/balena-sound#34]
Since the default PIN code is hard-coded and too easy to guess, it can be a problem for users of this project to not be able to change it. The environment variable `BLUETOOTH_PIN_CODE` seems to be a nice candidate for this purpose, and I'll send a PR soon which is going to implement this solution.

**Comment by barhun** [comment]
#35

**Comment by tmigone** [comment]
PIN code support implemented in #51 . Please do test and let us know any issues you experience, thanks!
