### ISSUE TITLE
Balena shutdown

### ISSUE THREAD

**Issue by bloppe** [balena-io-projects/balena-sound#42]
Hi, 

I've just completed my first Balena project, the Balenasound raspberry pi build. It works great, but I am not sure how to remotely shut my pi down without just turning it off at the wall. Help please

**Comment by AlexProgrammerDE** [comment]
![Screenshot_20191008-113829_Samsung Internet](https://user-images.githubusercontent.com/40795980/66385268-7fe1ae00-e9c0-11e9-8a21-193616c78ec2.jpg)
![Screenshot_20191008-113810_Samsung Internet](https://user-images.githubusercontent.com/40795980/66385269-7fe1ae00-e9c0-11e9-8d39-27f12edff61b.jpg)
![Screenshot_20191008-113748_Samsung Internet](https://user-images.githubusercontent.com/40795980/66385275-807a4480-e9c0-11e9-9021-17582df575a6.jpg)
![Screenshot_20191008-113900_Samsung Internet](https://user-images.githubusercontent.com/40795980/66385276-807a4480-e9c0-11e9-887c-d4a6abf5d341.jpg)
![Screenshot_20191008-113855_Samsung Internet](https://user-images.githubusercontent.com/40795980/66385277-8112db00-e9c0-11e9-970a-069ed58e639e.jpg)
![Screenshot_20191008-113731_Samsung Internet](https://user-images.githubusercontent.com/40795980/66385279-8112db00-e9c0-11e9-87f3-3fec6fcd4349.jpg)

**Comment by AlexProgrammerDE** [comment]
Go to balena then login then click on the blue device name then click on the arrow and then click shutdown.

**Comment by chrisys** [comment]
@AlexProgrammerDE thanks for replying here! 👍 As mentioned above, the shutdown option is on the dashboard in the device screen under the dropdown.

![Screenshot 2019-10-08 at 11 02 43](https://user-images.githubusercontent.com/521698/66387144-45294700-e9bb-11e9-8c01-6f050aee3142.png)
