### ISSUE TITLE
Spotify Connect & Podcasts

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-projects/balena-sound#49]
I noticed that I can't stream Podcasts, although music works just fine.

I believe this could be since Podcasts are being considered "mixed" content, with both Audio & Video, although I doubt video is supported in the regular Spotify client.

Is there any known workaround to possibly stream podcasts too?

**Comment by AlexProgrammerDE** [comment]
How about bluetooth? This should be a workaround for the next time.

**Comment by AlexProgrammerDE** [comment]
And what do you mean with Spotify airplay & Podcast? Do you mean Spotify connect?

**Comment by dimitrisnl** [comment]
@AlexProgrammerDE Yes, my bad. I meant Spotify Connect.
Bluetooth is definitely an option, just wondering.

**Comment by dimitrisnl** [comment]
Closing. It's something on Spotify's side as I read through some discussions on their boards.

**Comment by dmnc-net** [comment]
Even this is closed issue I can confirm that you can't play podcasts thru Spotify Connect devices (at least based on librespot), only on native Spotify applications.

**Comment by AlexProgrammerDE** [comment]
Do you know a alternative?

**Comment by dimitrisnl** [comment]
relevant thread on librespot https://github.com/librespot-org/librespot/issues/90

**Comment by AlexProgrammerDE** [comment]
I am finished. It could take the developer a long time to integrate it from librespot-java to librespot. I saw that it is not perfect implemented to people which have no premium like me but if you have premium should it work. People without premium can connect to it and in this case is the client will crash. I hope you will bring me good result when you try it. Sorry that i make it this way but my fork is at the moment in a PR. I think you can add this files by yourself.
[files.zip](https://github.com/balena-io-projects/balena-sound/files/3789885/files.zip)
