### ISSUE TITLE
Sound-Supervisor failing to build

### ISSUE THREAD

**Issue by DavidTripa** [balena-io-projects/balena-sound#502]
I've tried pushing the balena-sound project to balenaCloud several times using balena CLI but the Sound-Supervisor service keeps failing to build. 

[Error]               Service: sound-supervisor
[Error]                 Error: The command '/bin/sh -c npm run build' returned a non-zero code: 2
[Info]              Built on arm06
[Error]             Not deploying release.

**Comment by DavidTripa** [comment]
One-click deploy also not working. Same error. balena-sound is no longer deployable. Can someone please help with this? 

npm 
ERR! code
 ELIFECYCLE

npm 
ERR!
 errno 2

npm ERR!
 sound-supervisor@1.0.0 build: `npm run clean && tsc --project tsconfig.json && cp -R src/ui build/ui && cp -R src/audio-block build/audio-block`
npm 
ERR!
 Exit status 2

npm ERR!
 
npm
 ERR!
 Failed at the sound-supervisor@1.0.0 build script.
npm
 ERR! This is probably not a problem with npm. There is likely additional logging output above.

The command '/bin/sh -c npm run build' returned a non-zero code: 2

**Comment by eiddor** [comment]
Hmmm strange - I was able to build and push the latest version for my RPi4 without a problem.

What kind of device are you using?

**Comment by DavidTripa** [comment]
I have a RPi3B+ using RPi3 (64bit OS).

**Comment by eiddor** [comment]
Hmmm - The only difference that I can see is that mine says:

 `[Info]              Building on arm03`

I just downloaded the latest Balena CLI and now it says:

`[Info]              Building on arm04`

Still builds and deploys, though.

```
[logging]           [>                                                        ]
[sound-supervisor]   ---> 284c124f41f8
[logging]           [>                                                        ]
[sound-supervisor]  Step 2/15 : WORKDIR /usr/src
[logging]           [>                                                        ]
[sound-supervisor]  Using cache
[logging]           [>                                                        ]
[sound-supervisor]   ---> 4327aeb9024b
[logging]           [>                                                        ]
[sound-supervisor]  Step 3/15 : COPY core/sound-supervisor/package*.json ./
[logging]           [>                                                        ]
[sound-supervisor]  Using cache
[logging]           [>                                                        ]
[sound-supervisor]   ---> 32abe0fd8d6a
[logging]           [>                                                        ]
[sound-supervisor]  Step 4/15 : RUN npm install
[logging]           [>                                                        ]
[sound-supervisor]  Using cache
[logging]           [>                                                        ]
[sound-supervisor]   ---> 0b2f5bbe413f
[logging]           [>                                                        ]
[sound-supervisor]  Step 5/15 : COPY core/sound-supervisor/src ./src
[logging]           [>                                                        ]
[sound-supervisor]  Using cache
[logging]           [>                                                        ]
[sound-supervisor]   ---> a813861981c4
[logging]           [>                                                        ]
[sound-supervisor]  Step 6/15 : COPY core/sound-supervisor/tsconfig.json .
[logging]           [>                                                        ]
[sound-supervisor]  Using cache
[logging]           [>                                                        ]
[sound-supervisor]   ---> 8bc8c07c3357
[logging]           [>                                                        ]
[sound-supervisor]  Step 7/15 : RUN npm run build
[logging]           [>                                                        ]
[sound-supervisor]  Using cache
[logging]           [>                                                        ]
[sound-supervisor]   ---> 5d737bc0738a
[logging]           [>                                                        ]
[sound-supervisor]  Step 8/15 : COPY VERSION .
[logging]           [>                                                        ]
[sound-supervisor]  Using cache
[logging]           [>                                                        ]
[sound-supervisor]   ---> 68981cc0a947
[logging]           [>                                                        ]
[sound-supervisor]  Step 9/15 : FROM balenalib/raspberrypi4-64-alpine-node:12
```

**Comment by eiddor** [comment]
It looks like it might be an upstream issue with [this image](https://hub.docker.com/r/balenalib/raspberrypi3-alpine-node), which was updated a couple of days ago.  I'm not versed enough in the Balena build tools to know for sure, but when I forced my sound-supervisor `Dockerfile` to use that one, I got the same failures.

I would try opening an issue here: https://github.com/balena-io-library/base-images/issues

**Comment by mikew5446** [comment]
Thanks - I have logged in the base-images support.

**Comment by guybridge** [comment]
I was able to fix by ignoring the types here in soundAPI.ts

`
`    this.api.get('/audio', asyncHandler(async (_req, res) => res.json(await this.audioBlock.getInfo())))
    this.api.get('/audio/volume', asyncHandler(async (_req, res) => res.json(await this.audioBlock.getVolume())))
    this.api.post('/audio/volume', asyncHandler(async (req, res) => res.json(await this.audioBlock.setVolume(req.body.volume))))
    this.api.get('/audio/sinks', asyncHandler(async (_req, res) => res.json(stringify(await this.audioBlock.getSinks()))))``

`    this.api.post('/device/restart', asyncHandler(async (_req, res) => res.json(await restartDevice())))
    this.api.post('/device/reboot', asyncHandler(async (_req, res) => res.json(await rebootDevice())))
    this.api.post('/device/shutdown', asyncHandler(async (_req, res) => res.json(await shutdownDevice())))`

**Comment by tmigone** [comment]
Hey everyone, just created #503 to address this issue. Turns out it's an update to a dependency that broke the types. I'll merge the PR ASAP
