### ISSUE TITLE
Newlines are in DOS format

### ISSUE THREAD

**Issue by Crinfarr** [balena-io-projects/balena-sound#61]
Current version errors out with 
`$'\r': command not found`
as DOS newlines are \r\n instead of a Unix \n.  Easily fixed with find/replace.

**Comment by tmigone** [comment]
Hi @Crinfarr , could you specify what file(s) are you talking about? Thank you.

**Comment by Crinfarr** [comment]
Specifically the start.sh files are causing trouble, but I would suggest fixing all executed files just in case.

**Comment by AlexProgrammerDE** [comment]
Hi @Crinfarr i don´t know if we have the same problem. Are you using Windows?

**Comment by Crinfarr** [comment]
My computer is windows, but it shouldn't matter with a direct clone of the repo AFAIK...

**Comment by AlexProgrammerDE** [comment]
Yes i did also think that until i saw that. Could you please try to dowload the Zip file (This is under the url *.git). Then you need to spawn a shell in the uzipped folder. In the shell can you push with the balena-cli like before.

**Comment by VictorGamer072YT** [comment]
Yup, had to do this, else it would not work, thanks

**Comment by chrisys** [comment]
@Crinfarr when you clone a repo with git, it will change the line endings to those used by your system and then switch back when you commit. See here for info: https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings
