### ISSUE TITLE
Sound delay (approx 1 sec)

### ISSUE THREAD

**Issue by supermooshman** [balena-io-projects/balena-sound#64]
I'm experiencing a sound delay of approximately 1 second making it useless to watch videos. Is this expected behavior?

Using Raspberry Pi 3b

**Comment by chrisys** [comment]
@supermooshman take a look at this line https://github.com/balena-io-projects/balena-sound/blob/bcb076810271a06fc6402693afc65ea18a9d1a76/bluetooth-audio/start.sh#L57

You can try reducing the buffer time and see if that helps.

**Comment by supermooshman** [comment]
thanks!

**Comment by Micinkator** [comment]
did you fix the delay? where do i find the config once the service / app is running inside the Raspberry?

**Comment by cloutier72** [comment]
This Project is a major disappointment. I use an inexpensive Bluetooth adapter to connect a “Peloton” bike to an older Bose wave radio. The adapter “forgets” the pairing settings, leading me to have to reconnect the two. 
I thought that a raspberry pi 4 would offer some stability. Wrong... it qwas even worse. The peloton/raspberry pi handshake actually froze the peloton app. 

Same thing for YouTube. There’s a frustrating delay between the image and sound. 

So... in conclusion...  great use of a raspberry pi for music - only.
