### ISSUE TITLE
Request: Add Airplay.

### ISSUE THREAD

**Issue by ReubenBTalbott** [balena-io-projects/balena-sound#7]
No idea if this is possible to add to Balena-sound but could Airplay be added?

**Comment by chrisys** [comment]
Sure, this is something we can look at! Thanks for the feedback

**Comment by AlexProgrammerDE** [comment]
Maybe this could be a good help: https://github.com/mikebrady/shairport-sync

**Comment by chrisys** [comment]
There's also the service here already set up to run on balena which you could copy in to the project https://github.com/balena-io-projects/boombeastic/tree/master/airplay

**Comment by chrisys** [comment]
@ReubenBTalbott I am testing support for this in this PR https://github.com/balena-io-projects/balena-sound/pull/32 - if you get a chance give it a try and let me know what you think!

**Comment by ReubenBTalbott** [comment]
I just tried it and so far it works perfectly, thanks!

**Comment by chrisys** [comment]
Thanks for testing it, I've now merged this to master 👍
